# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afb0d942a40c726918836c95976b37dd08dc2fab6e05d0e64b60bcfd3f20ec68bb7868ab47c685a942d5d29e6630054efb3c54540d9929ec3903013b501685b7

test:
  secret_key_base: dd4aece7afe329a96a89b218c8afeee7bbda98518ccc4cecc01801265c4fc75c2fe93cbec104eb1d9c74de802ae5bb70609daace69b49adb3dca343c235fc903

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
